#pragma once

#ifndef PI_API
#define PI_API __attribute__((visibility("default")))
#endif

#ifdef __cplusplus
extern "C" {
#endif

PI_API
double approximate_pi_c(const int num_points);

#ifndef _NOFORTRAN
PI_API
double approximate_pi_fortran(const int num_points);
#endif

#ifdef __cplusplus
}

/* export macros for library generated by CMake */
/*
#ifndef PI_API
#include "pi_export.h"
#define PI_API PI_EXPORT
#endif

#ifdef __cplusplus
extern "C" {
#endif

PI_API
double approximate_pi_c(const int num_points);

PI_API
double approximate_pi_fortran(const int num_points);

#ifdef __cplusplus
}
*/
#endif
