.SUFFIXES: .o .c .cu

exe: mpic.o mpicu.o
	$(CC) $(CFLAGS) $(LDFLAGS) $^ -o $@

mpic.o: mpic.c
	$(CC) $(CFLAGS) -c $< -o $@
	@echo

mpicu.o: mpicu.cu
	$(NVCC) $(CPPFLAGS) $(CXXFLAGS) -c -I$(CUDATOOLKIT_HOME)/include $< -o $@
	@echo

clean:
	rm -f *.o
