#!/bin/bash
#
# VV=jgphpc/mpich:ub1804_cuda92_mpi314_osu
# DD=Dockerfile.ubuntu1804lts+cuda92+mpich314+osu
#
# docker build -f ./$DD -t $VV .
# docker push $VV
# docker run -it $VV bash
# ---
# module use /apps/dom/SI/modulefiles ;mll sarus/1.0.0-rc5-daint
# sarus pull jgphpc/mpich:ub1804_cuda92_mpi314_osu561
# srun -Ausup -Cgpu -N2 -t2 sarus run --mpi jgphpc/mpich:ub1804_cuda92_mpi314_osu561 /usr/local/libexec/osu-micro-benchmarks/mpi/pt2pt/./osu_latency
# srun --pty -n1 sarus run -t jgphpc/mpich:ub1804_cuda92_mpi314_osu561 bash
FROM jgphpc/mpich:ub1804_cuda92_mpi314

RUN apt-get update \
    && apt-get install -y ca-certificates patch

RUN cd /tmp \
    && wget http://mvapich.cse.ohio-state.edu/download/mvapich/osu-micro-benchmarks-5.6.1.tar.gz \
    && wget https://raw.githubusercontent.com/jgphpc/jgphpc/master/hpc/containers/mpich/osu.patch \
    && tar xf osu-micro-benchmarks-5.6.1.tar.gz \
    && cd osu-micro-benchmarks-5.6.1 \
    && patch mpi/pt2pt/osu_latency.c ../osu.patch \
    && ./configure --prefix=/usr/local CC=$(which mpicc) CFLAGS=-O3 \
    && make -j2 \
    && make install \
    && cd .. \
    && rm -rf mpich-3.1.4* \
    && rm -rf osu-micro-benchmarks-5.6.1*

WORKDIR /usr/local/libexec/osu-micro-benchmarks/mpi/pt2pt
CMD ["mpiexec", "-n", "2", "-bind-to", "core", "./osu_latency"]
