#!/bin/sh

 course02@daint104:~/bin/mydevice$
srun -C gpu -n1 -t1 exe.dai
srun: job 1696988 queued and waiting for resources
srun: job 1696988 has been allocated resources
=== get_gpu_info ===
Process 0 on nid out of 0 Device 0 (Tesla P100-PCIE-16GB)

=== get_more_gpu_info ===
Device 0: "Tesla P100-PCIE-16GB"
  CUDA Driver Version / Runtime Version     8.0 / 8.0
  CUDA Capability Major/Minor version number:    6.0
  (56) Multiprocessors, ( 64) CUDA Cores/MP:     3584 CUDA Cores
  GPU Max Clock rate:                            1329 MHz (1.33 GHz)
  Theoretical peak performance per GPU:          4761 Gflop/s
  Maximum number of threads per multiprocessor:  2048
  Peak number of threads:                        114688 threads
  Maximum number of threads per block:           1024

=== /proc/driver/nvidia/version ===
NVRM version: NVIDIA UNIX x86_64 Kernel Module  375.39  Tue Jan 31 20:47:00 PST 2017





## GPU                          Compute Capability
Tesla V100                      7.0                     cuda/90
Tesla P100                      6.0                     cuda/80
Tesla K80                       3.7                     cuda/7.x
Tesla K40                       3.5
Tesla K20                       3.5
Tesla C2075                     2.0
Tesla C2050/C2070               2.0
Tesla C1060                     1.3
Tesla C870                      1.0
