#!/bin/bash
# 
# VV=jgphpc/openmpi:ub1804_cuda92_mpi401
# DD=Dockerfile.ubuntu1804lts+cuda92+openmpi401
# 
# docker build -f ./$DD -t $VV .
# docker push $VV
# docker run -it $VV bash
# docker run $VV cat /etc/os-release
#   NAME="Ubuntu"
#   VERSION="18.04.1 LTS (Bionic Beaver)"
# https://hub.docker.com/r/nvidia/cuda/
# new: https://gitlab.com/nvidia/cuda/blob/ubuntu18.04/9.2/devel/Dockerfile
# old: https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/9.2/devel/Dockerfile 
FROM nvidia/cuda:9.2-devel-ubuntu18.04

RUN apt-get update \
    && apt-get install -y \
        bison \
        file \
        g++ \
        gcc \
        make \
        gdb \
        wget \
        strace \
        --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
#         gfortran \
#         realpath \

RUN wget -q https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.1.tar.gz \
    && tar xf openmpi-*.tar.gz \
    && cd openmpi-* \
    && ./configure --with-slurm=no --prefix=/usr/local \
    && make -j3 all install \
    && cd .. \
    && rm -rf openmpi-*

RUN ldconfig
RUN cd /openmpi-3.1.3/examples && mpicc hello_c.c -o hello_c.exe

# WORKDIR /usr/local/libexec/osu-micro-benchmarks/mpi/pt2pt
# CMD ["mpiexec", "-n", "2", "-bind-to", "core", "./osu_latency"]
