#!/bin/bash
#
# VV=jgphpc/mvapich:ub1804_cuda92_mpi231_osu561
# DD=Dockerfile.ubuntu1804lts+cuda92+mvapich231+osu561
#
# docker build -f ./$DD -t $VV .
# docker push $VV
# docker run -it $VV bash
# docker run $VV cat /etc/os-release
#   NAME="Ubuntu"
#   VERSION="18.04.1 LTS (Bionic Beaver)"
# https://hub.docker.com/r/nvidia/cuda/
# new: https://gitlab.com/nvidia/cuda/blob/ubuntu18.04/9.2/devel/Dockerfile
# old: https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/9.2/devel/Dockerfile 
# 
# sarus pull jgphpc/mvapich:ub1804_cuda92_mpi231_osu561
# srun -N2 sarus run --mpi jgphpc/mvapich:ub1804_cuda92_mpi231_osu561 /usr/local/libexec/osu-micro-benchmarks/mpi/pt2pt/./osu_latency
FROM jgphpc/mvapich:ub1804_cuda92_mpi231

RUN apt-get update \
    && apt-get install -y ca-certificates patch

RUN cd /tmp \
    && wget http://mvapich.cse.ohio-state.edu/download/mvapich/osu-micro-benchmarks-5.6.1.tar.gz \
    && wget https://raw.githubusercontent.com/jgphpc/jgphpc/master/hpc/containers/mpich/osu.patch \
    && tar xf osu-micro-benchmarks-5.6.1.tar.gz \
    && cd osu-micro-benchmarks-5.6.1 \
    && patch mpi/pt2pt/osu_latency.c ../osu.patch \
    && ./configure --prefix=/usr/local CC=$(which mpicc) CFLAGS=-O3 \
    && make -j2 \
    && make install \
    && cd .. \
    && rm -rf mpich-3.1.4* \
    && rm -rf osu-micro-benchmarks-5.6.1*

WORKDIR /usr/local/libexec/osu-micro-benchmarks/mpi/pt2pt
CMD ["mpiexec", "-n", "2", "-bind-to", "core", "./osu_latency"]
